{{- if .Values.serviceWatcher.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.serviceWatcher.role.name }}
  labels:
    {{- include "gw-component-chart.labels" . | nindent 4 }}
rules:
  - apiGroups:
      {{- toYaml .Values.serviceWatcher.role.apiGroups | nindent 6 }}
    resources:
      {{- toYaml .Values.serviceWatcher.role.resources | nindent 6 }}
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.serviceWatcher.roleBinding.name }}
  labels:
    {{- include "gw-component-chart.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceWatcher.serviceAccountName }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Values.serviceWatcher.role.name }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}